### ISSUE TITLE
Add attribute to specify additional xgettext options

### ISSUE THREAD

**Issue by theory** [theory/dist-zilla-localetextdomain#2]
Add a `[LocaleTextDomain]` attribue to allow developers to specify additional and/or replacement options to `xgettext` in the `dist.ini` file. One reason someone might want to use it has been suggested by [Locale::TextDomain](https://http://metacpan.org/module/Locale::TextDomain) author Guido Flohr:

> In Imperia we have another problem: We define aliases for all
> double-underscore functions that have three underscores.  In other
> words, we have __"hello" and ___"hello".  At runtime, the functions are
> just aliases.  But the triple underscore functions are used for marking
> strings that are less important, for example esoteric error messages
> (eg. ___"This should not happen!").
> 
> That allows us to ship incomplete translations for certain languages,
> only containing the "important", usually user visible stuff.  Probably
> quite an exotic setup, but I've often seen people using custom functions
> for marking their strings.
> 
> Is it possible to control the exact invocation of xgettext for allowing
> such setups?

So, yeah, give folks the ability to do that sort of thing.

**Comment by theory** [comment]
Thanks for taking care of a bunch of these, @chazmcgarvey! One request: Don't forget to update `Changes`.

**Comment by chazmcgarvey** [comment]
No problem. I've updated `Changes` on master. I've been testing the new changes on a project over the past couple of months, and they've worked pretty well for me so HEAD could be a release candidate. What do you think?

**Comment by theory** [comment]
DO EEEET!
